version: 1
runtime: python36
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  expiration: 14d
- url: /admin.*
  script: admin.app
  login: admin
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.10.3"
- name: markupsafe
  version: "1.1.1"
